### ISSUE TITLE
Adding the plugin to official Kodi repo?

### ISSUE THREAD

**Issue by trsqr** [hirsivaja/plugin.video.areena#17]
Hi,

Good job with the plugin! Are there plans to add it into the official Kodi repo?

Thanks.
-olli

**Comment by hirsivaja** [comment]
Interesting idea. Going to think about that. Doesn't seem to be too difficult to do

**Comment by hirsivaja** [comment]
I have looked into it and have decided not to do it because the legal issues seem too complicated (licenses, image copyright etc.)
