### ISSUE TITLE
Missing features.

### ISSUE THREAD

**Issue by raspikodi4ever** [hirsivaja/plugin.video.areena#18]
Not so much issues, but two major feature requests:
1. Support for the very recent Areena 4 hours(!) server side time shift would be cool.
2. FlickFetch style download of any available Areena stream and use of timer for live. 
http://flickfetch.bplaced.net

Love this add-on on Raspberry Pi Kodi - thank you plenty for it and keep up the good work!

**Comment by hirsivaja** [comment]
1. What do you mean? Could you elaborate?

2. I won't add a feature to download the streams. There are other options available for that like the tool you linked

**Comment by hirsivaja** [comment]
I am going to close this. But you can create a new issue with more information about the first topic. In general it is not a good practice to put several unrelated topics in one issue...
