### ISSUE TITLE
Update overwrites / forces to input credentials again

### ISSUE THREAD

**Issue by Huxely** [hirsivaja/plugin.video.areena#20]
I'm using plugin with LibreElec / Kodi Krypton 17.1, and noticed that it is capable of autoupdating this plugin. But after updating it, the plugin forced me to input my Areena credentials again, even though I already had working install, with working credentials. I'm not sure, if this is a feature/bug of the plugin, or Kodi, but It would be preferable not to overwrite old credentials.py or at least leave user the option, not to input the credential and use old, when installing new version.

**Comment by hirsivaja** [comment]
I haven't tried that auto-update, but my guess about what happened is that when you use the auto-update it removes all the existing files and replaces them with new ones from the GitHub. If you want it to preserve the credentials in the update add them through the settings menu. Do not use the credentials.py file.

**Comment by Huxely** [comment]
Ok, so this is a non issue. I've been using the plugin from almost the beginning and have had the credentials only on the credential.py file. If they are now stored separately in the settings (file?) that is persistent over updating, there is no problem. I'll close this one.
