### ISSUE TITLE
Support for Areena timeshift possible?

### ISSUE THREAD

**Issue by raspikodi4ever** [hirsivaja/plugin.video.areena#22]
http://yle.fi/aihe/artikkeli/2017/02/21/ajansiirto-ominaisuus-areenan-tv-kanavalahetyksiin

Sorry for the previous start that I forgot to return to.

Areena currently has this server side timeshift feature activated that can be used in regular web browsers, so shouldn't it be possible to implement it to Areena API plug in too, as it is a feature provided by Areena's side? It would be cool to be able to browse back and forth in the open live stream and pause it without losing a moment in Kodi too and especially cool, if it would work in Raspberry Pi Kodi.

Also sorry to hear that no plans of implementing download feature to Areena Plug-in, since FlickFetch dev claims to have no skills(?) to port his software to Kodi and make it compatible with Raspberry Pi. Problem is that Windows doesn't run in Rasp, but Rasp is convenient to keep on-line all the time as it's consuming very little energy, much less than the most energy efficient Windows laptop for example.

I myself haven't found by googling a generic working download addon for Kodi, that would work for any video stream available. If there's one, please name it, so I can search for further info about it.

Anyway, this timeshift alone would be a great improvement in overall usability of the Areena API plug-in, if it's possible to implement and why shouldn't it be?

**Comment by hirsivaja** [comment]
Sorry for the long delay. The time shift feature is not added to the YLE API so it would require quite an effort to implement. Also it would probably require a custom video player for the Kodi. If the API is updated to include the time shift I can try to implement this.

As an alternative you can find the currently playing program from the list of programs and start watching it from the beginning. Then you also have the option to pause the program and skip any part you don't want to see.
