### ISSUE TITLE
News and Sports

### ISSUE THREAD

**Issue by Ommik345** [hirsivaja/plugin.video.areena#24]
News and sports not supported in API - any idea why and/or would there be a way around it?

**Comment by Ommik345** [comment]
After making some searches and playing with YLE API myself seems that this is just how it is at this point.. 

https://forum.kodi.tv/showthread.php?tid=144457&page=39

this plugin is great btw! Will close the issue.

**Comment by hirsivaja** [comment]
Seems like the API is now allowing usage of news and sport content as well. That content is available in the newer versions of the plugin
