### ISSUE TITLE
Live-TV not working on Raspberry Pi 3

### ISSUE THREAD

**Issue by StBeBe** [hirsivaja/plugin.video.areena#25]
Live-TV feature is not always working on RPi3. Sometimes it is working and sometimes it throws an error and does not show the list of available broadcasts.

Copypaste from kodi.log when error happens:

> 19:03:52.510 T:1911595008   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
> 19:03:55.700 T:1703002880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.UnicodeEncodeError'>
>                                             Error Contents: 'ascii' codec can't encode characters in position 26-27: ordinal not in range(128)
>                                             Traceback (most recent call last):
>                                               File "/home/pi/.kodi/addons/plugin.video.areena/main.py", line 1122, in <module>
>                                                 router(sys.argv[2][1:])
>                                               File "/home/pi/.kodi/addons/plugin.video.areena/main.py", line 1108, in router
>                                                 live_tv_channels(path)
>                                               File "/home/pi/.kodi/addons/plugin.video.areena/main.py", line 512, in live_tv_channels
>                                                 get_color('menuItemColor'),  get_translation(32072) + title))
>                                             UnicodeEncodeError: 'ascii' codec can't encode characters in position 26-27: ordinal not in range(128)
>                                             -->End of Python script error report<--
> 19:03:55.745 T:1911595008   ERROR: GetDirectory - Error getting plugin://plugin.video.areena/?action=live
> 19:03:55.746 T:1911595008   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.areena/?action=live) failed
>

**Comment by hirsivaja** [comment]
I tried to fix the issue. Please check if it solves your problem.

**Comment by StBeBe** [comment]
This certainly seems to fix the issue. 

I updated plugin today and tested live-tv behavior many times. It is now working every time.

Thank you very much!
