### ISSUE TITLE
Authorization fails

### ISSUE THREAD

**Issue by kelluvampi** [hirsivaja/plugin.video.areena#27]
Error messages are pretty same as in the previous issue: "Provide some error message to kodi user interface when authorization with keys fail".

NOTICE: Starting Kodi from Debian (17.6 Debian package version: 2:17.6+dfsg1-2+b1). Platform: Linux x86 64-bit
.
.
.
 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
      - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.IOError'>
    Error Contents: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x7f4b706af680>)
    Traceback (most recent call last):
      File "/home.ssd/kodi/.kodi/addons/plugin.video.areena/main.py", line 1183, in <module>
        router(sys.argv[2][1:])
      File "/home.ssd/kodi/.kodi/addons/plugin.video.areena/main.py", line 1169, in router
        live_tv_channels(path)
      File "/home.ssd/kodi/.kodi/addons/plugin.video.areena/main.py", line 555, in live_tv_channels
        data = get_areena_api_json_data('programs/schedules', 'now.json', ['service=' + service])
      File "/home.ssd/kodi/.kodi/addons/plugin.video.areena/main.py", line 65, in get_areena_api_json_data
        response = get_url_response(url)
      File "/home.ssd/kodi/.kodi/addons/plugin.video.areena/main.py", line 939, in get_url_response
        raise error
    IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x7f4b706af680>)
    -->End of Python script error report<--
ERROR: GetDirectory - Error getting plugin://plugin.video.areena/?action=live
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.areena/?action=live) failed

Yle keys are checked (plugin used to work with these)
Version of the plugin: 2.4.4.

**Comment by hirsivaja** [comment]
I have not been able to reproduce this on my environments. Does this happen every time for you?

Is it happening only in the Live TV section?

**Comment by hirsivaja** [comment]
Closed since no information provided. Seems to work in current version.
