### ISSUE TITLE
Installment

### ISSUE THREAD

**Issue by kaupmat** [hirsivaja/plugin.video.areena#31]
Can somebody be so kind and help with how this can be installed on Kodi?

**Comment by hirsivaja** [comment]
You can follow these instructions: https://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files
You can download the zip from the main page https://github.com/hirsivaja/plugin.video.areena/archive/master.zip

**Comment by kaupmat** [comment]
Thank you so much :) Kiitos!

**Comment by kaupmat** [comment]
This is where I been stuck :)

Kodi 17.6 on Amazon Fire TV Cube
Unknown sources enabled
System, File Manager, Add source, https://github.com/hirsivaja/plugin.video.areena/archive/master.zip
and alot of similar and wrong sources tried to input here ;)

So when I try "install from zip file" it shows no file.
