### ISSUE TITLE
Yle Api will require https and SNI, (server name indication)

### ISSUE THREAD

**Issue by MagnusA** [hirsivaja/plugin.video.areena#32]
Message from Yle:

> Hei!
> 
> Alkaen 1.11. Yle API vaatii sitä hyödyntävissä sovelluksissa HTTPS- ja SNI-tuen (Server Name Indication). Selainsovelluksissa tuki on yleensä kunnossa. APIa kannattaa jatkossa kutsua aina HTTPS-protokollaa käyttäen.
> 
> Lisätietoja:
> https://en.wikipedia.org/wiki/Server_Name_Indication
> https://developer.yle.fi/
> 
> Lähetimme tämän viestin, koska tällä sähköpostiosoitteella on avain Yle APIin.
> 
> ---
> 
> Hello,
> 
> Starting November 1st, Yle API will require applications to support HTTPS and SNI (Server Name Indication). Browser-based applications usually support both by default. We recommend to always call the API using HTTPS.
> 
> More information:
> https://en.wikipedia.org/wiki/Server_Name_Indication
> https://developer.yle.fi/en/index.html
> 

does the plugin fulfill these requirements?

**Comment by hirsivaja** [comment]
The plugin uses the HTTPS as default. SNI support comes from Python and you need to have a version that is not too old. The Wikipedia article in your message ([support](https://en.wikipedia.org/wiki/Server_Name_Indication#Support) says that SNI has been supported in Python since 2014.

**Comment by kaskelotti** [comment]
My Kodi setup on Raspberry has been mostly shelved for the past months, but everything seemed to work at least on the audio side as I tried it today. So I'm guessing this was a non-issue and can be closed.
