### ISSUE TITLE
Favourites, what are the differences

### ISSUE THREAD

**Issue by ikke-t** [hirsivaja/plugin.video.areena#33]
Hi,

Thanks for the nice plugin. One small thing bothers, I don't quite get how stuff goes to favourites from here. There seems to be two favourites, the general Favourites in Kodi main menu. Then there is Favourites in plugin opening menu. Then each item let's to select

* Add series to favourites
* Add item to favourites
* Add to favourites

It would be more clear if the menu told to which favourites it means, the plugin menu or main menu? E.g:

* Add series to Areena favourites
* Add series to Kodi favourites

and the same for the remove from Favourites

**Comment by kaskelotti** [comment]
I agree. Especially when new to Kodi this is very confusing. I also wondered at first where the favourites went.

It seems that texts related to this plugin are part of the [localization files](https://github.com/hirsivaja/plugin.video.areena/blob/3cda7a0ae887281ae5274a6e5ba9afb22e3537a5/resources/language/Finnish/strings.po#L119). Change to this should be trivial.

I don't know how the Kodi plugin structure is, but I assume that the context menu text for adding to Kodi favourites cannot be changed.

**Comment by hirsivaja** [comment]
I changed the one adding the favourite to plugin Favourites. Maybe the other one could be changed as well but since it is coming from Kodi it is at least harder one to change
