### ISSUE TITLE
mark watched?

### ISSUE THREAD

**Issue by ikke-t** [hirsivaja/plugin.video.areena#40]
I don't know if YLE API provides the info about if episode is watched or not, but I just opened the series "rauhantekijä", and it doesn't show if I've watched the episodes or not. I recall some of the plugins show if you have watched the episode. There is different kind of icon next to show.

I wonder if it's possible to have similar marking with yle areena? Here is what it looks like now:

![eka-800](https://user-images.githubusercontent.com/1146409/99576856-2fba8500-29e3-11eb-87cc-6010894ce2b0.jpg)

and here's what it looks in Netflix plugin:

![toka-800](https://user-images.githubusercontent.com/1146409/99576800-1addf180-29e3-11eb-892b-49994f08e1ff.jpg)

Of course, I'd not like to loose the thumbnails :D

**Comment by hirsivaja** [comment]
To see the mark you need to select some other view type. Looks like you have "List" in Netflix. It should show the mark also in Areena plugin with that view type but no thumbnails. It can also depend on the skin you use in Kodi.

**Comment by ikke-t** [comment]
Haa, thanks for the leason :) So it does, I never knew there are different types of views.
