### ISSUE TITLE
Areena videos do not play

### ISSUE THREAD

**Issue by karsta62** [hirsivaja/plugin.video.areena#46]
LibreELEC (community): nightly-20210407-84b62ff (RPi2.arm) with Kodi 19.

Everything else works (including search and radio play), but video playback does not.
I also disabled VPN Manager but that did not change a thing. (The log had it enabled).

Activated kodi's debug logging and grep'd areena from it. Attached.
[areena.log](https://github.com/hirsivaja/plugin.video.areena/files/6271239/areena.log).

**Comment by karsta62** [comment]
Am I really the only one..?

**Comment by hirsivaja** [comment]
Hi Karsta,
according to this https://libreelec.tv/2021/03/libreelec-leia-10-0-b1/
the LibreELEC is not yet supporting Kodi 19 for Raspberry PI 2.
"RPi 2/3 are still in development targetting an LE10.2 release."

**Comment by karsta62** [comment]
That's why I must run the nightlies. There was a feature only in Kodi19 which I needed. Which I don't remeber what it actually was right now...oh yes. It's the youtube addon, "Tubed". Only in Kodi19. 
The "youtube-addon" stopped working claiming that my quota is full, which is definitely not true.

Everything else is working nicely except the areena addon.
If there is a beta LibreElec already, I must try finding it. The download page does not have it.

**Comment by arpejupe** [comment]
I have the same problem in ubuntu 20.10 and Kodi 19.

There seems to be several issues:

`2021-04-20 21:36:29.659 T:6472  WARNING <general>: CPythonInvoker(22, /home/ubuntu/.kodi/addons/plugin.video.areena/main.py): the python script "/home/ubuntu/.kodi/addons/plugin.video.areena/main.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2021-04-20 21:36:29.659 T:6472     INFO <general>: Python interpreter stopped
2021-04-20 21:36:29.659 T:6472    DEBUG <general>: Thread LanguageInvoker 140632303679232 terminating`

`2021-04-20 21:37:32.549 T:6479    ERROR <general>: ffmpeg[0x55dd79b66e90X]: [hls] Error when loading first segment 'https://ylekaodamd.akamaized.net/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_eixdcnhq/v/1/ev/6/flavorId/1_brve7br5/name/a.mp4/index.m3u8/seg-1-v1-a1.ts?__hdnea__=st=1618943847~exp=1619030247~acl=/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_eixdcnhq/v/1/ev/6/flavorId/1_brve7br5/name/a.mp4/index.m3u8/*~hmac=0be60dcbfa274a37dcd320b4dd9885c24849323ae1590d146fc06329d15ddb97'
2021-04-20 21:37:32.552 T:6479    DEBUG <general>: Error, could not open file (2) https://ylekaodamd.akamaized.net/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_eixdcnhq/v/1/ev/6/flavorId/1_,brve7br5,wr5i1arw,ext9x185,mfpambmt,/name/a.mp4/index.m3u8.urlset/master.m3u8?__hdnea__=st=1618943805~exp=1618958205~acl=/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_eixdcnhq/v/1/ev/6/flavorId/1_*~hmac=23388c4dc984c89eeb0d1ef08c9f03dcafce5eb7bc98ac1cdde630a9cc13912f`


Also the icon of the addon is missing from the add-on menu, is it deliberately removed? I was able to fix it by adding it in addion.xml as resource

**Comment by hirsivaja** [comment]
Sorry, didn't look into this earlier.
But anyway now it seems to be irrelevant since the API is disabled.
Closing this issue...

**Comment by karsta62** [comment]
Does that mean that YLE areena plugin is no more?

**Comment by hirsivaja** [comment]
Sadly yes
